# Generated by Django 6.0.3 on 2026-03-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedlink',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='sharedlink',
            name='permission',
            field=models.CharField(choices=[('view', 'View only'), ('download', 'Download'), ('edit', 'Edit')], default='view', max_length=10),
        ),
    ]
